// Consistent reason codes for usage gating
export const START_GATE_REASON = {
  RECORDING_NOT_ALLOWED: "RECORDING_NOT_ALLOWED",
  RTMP_NOT_ALLOWED: "RTMP_NOT_ALLOWED",
  DESTINATION_LIMIT_EXCEEDED: "DESTINATION_LIMIT_EXCEEDED",
  OVER_LIMIT: "OVER_LIMIT",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  USAGE_DOC_MISSING: "USAGE_DOC_MISSING",
} as const;

export type StartGateReason = typeof START_GATE_REASON[keyof typeof START_GATE_REASON];
