import type { CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  container: {
    minHeight: "100vh",
    background: "#000",
    color: "#fff",
    fontFamily: "system-ui, -apple-system, sans-serif",
    position: "relative",
    overflow: "hidden",
  },
  orb1: {
    position: "fixed",
    top: "5%",
    left: "5%",
    width: 400,
    height: 400,
    background: "rgba(220,38,38,0.1)",
    borderRadius: "50%",
    filter: "blur(100px)",
    pointerEvents: "none",
  },
  orb2: {
    position: "fixed",
    bottom: "10%",
    right: "10%",
    width: 500,
    height: 500,
    background: "rgba(59,130,246,0.08)",
    borderRadius: "50%",
    filter: "blur(120px)",
    pointerEvents: "none",
  },
  content: {
    position: "relative",
    zIndex: 10,
    maxWidth: 900,
    margin: "0 auto",
    padding: "32px 24px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 32,
  },
  title: {
    margin: 0,
    fontSize: 28,
    fontWeight: 700,
    background: "linear-gradient(to right, #fff, #fecaca)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  refreshBtn: {
    padding: "10px 20px",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.2)",
    borderRadius: 10,
    color: "#fff",
    cursor: "pointer",
    fontSize: 14,
  },
  loadingScreen: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    gap: 16,
  },
  spinner: {
    width: 40,
    height: 40,
    border: "3px solid rgba(220,38,38,0.3)",
    borderTopColor: "#dc2626",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  errorBanner: {
    background: "rgba(239,68,68,0.15)",
    border: "1px solid rgba(239,68,68,0.4)",
    borderRadius: 12,
    padding: "16px 20px",
    marginBottom: 24,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: "#fca5a5",
  },
  errorClose: {
    background: "transparent",
    border: "none",
    color: "#fca5a5",
    fontSize: 20,
    cursor: "pointer",
  },
  warningCard: {
    background: "linear-gradient(135deg, rgba(239,68,68,0.15), rgba(220,38,38,0.1))",
    border: "2px solid rgba(239,68,68,0.5)",
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    display: "flex",
    gap: 20,
    alignItems: "flex-start",
  },
  warningIcon: {
    fontSize: 40,
    flexShrink: 0,
  },
  warningContent: {
    flex: 1,
  },
  warningTitle: {
    margin: "0 0 8px",
    fontSize: 20,
    fontWeight: 700,
    color: "#fca5a5",
  },
  warningText: {
    margin: "0 0 16px",
    color: "#fecaca",
    lineHeight: 1.5,
  },
  warningActions: {
    display: "flex",
    gap: 12,
    alignItems: "center",
  },
  fixPaymentBtn: {
    padding: "12px 24px",
    background: "linear-gradient(135deg, #ef4444, #dc2626)",
    border: "none",
    borderRadius: 10,
    color: "#fff",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
  },
  supportLink: {
    color: "#fca5a5",
    textDecoration: "underline",
    fontSize: 14,
  },
  card: {
    background: "rgba(15,15,15,0.7)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(63,63,70,0.5)",
    borderRadius: 20,
    padding: 28,
    marginBottom: 24,
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  cardTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 600,
  },
  processingBadge: {
    fontSize: 13,
    padding: "6px 12px",
    background: "rgba(245,158,11,0.2)",
    color: "#fbbf24",
    borderRadius: 20,
  },
  planDisplay: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 24,
    marginBottom: 24,
    flexWrap: "wrap",
  },
  planInfo: {},
  planNameRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  planName: {
    fontSize: 32,
    fontWeight: 700,
  },
  statusBadge: {
    padding: "6px 14px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: 600,
  },
  planPrice: {
    marginBottom: 8,
  },
  priceAmount: {
    fontSize: 24,
    fontWeight: 700,
    color: "#ef4444",
  },
  pricePeriod: {
    fontSize: 14,
    color: "#9ca3af",
  },
  planDescription: {
    margin: 0,
    color: "#9ca3af",
    fontSize: 14,
  },
  billingDetails: {
    textAlign: "right",
  },
  detailRow: {
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 13,
    color: "#6b7280",
    marginRight: 8,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: 500,
  },
  daysLeft: {
    marginLeft: 8,
    color: "#3b82f6",
    fontSize: 13,
  },
  actionButtons: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
  },
  primaryBtn: {
    padding: "14px 28px",
    background: "linear-gradient(135deg, #dc2626, #ef4444)",
    border: "none",
    borderRadius: 12,
    color: "#fff",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 4px 20px rgba(220,38,38,0.3)",
  },
  secondaryBtn: {
    padding: "14px 28px",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.2)",
    borderRadius: 12,
    color: "#fff",
    fontSize: 15,
    fontWeight: 500,
    cursor: "pointer",
  },
  resetDate: {
    fontSize: 13,
    color: "#6b7280",
  },
  usageGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: 20,
  },
  usageItem: {},
  usageHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  usageLabel: {
    fontSize: 14,
    color: "#d1d5db",
  },
  usageValue: {
    fontSize: 13,
    color: "#9ca3af",
  },
  usageTrack: {
    height: 8,
    background: "rgba(63,63,70,0.5)",
    borderRadius: 4,
    overflow: "hidden",
  },
  usageFill: {
    height: "100%",
    borderRadius: 4,
    transition: "width 0.5s",
  },
  plansGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 20,
    marginTop: 20,
  },
  planCard: {
    background: "rgba(0,0,0,0.3)",
    border: "2px solid",
    borderRadius: 16,
    padding: 20,
    position: "relative",
    overflow: "hidden",
  },
  currentBadge: {
    position: "absolute",
    top: 12,
    right: -30,
    padding: "4px 40px",
    fontSize: 11,
    fontWeight: 700,
    color: "#fff",
    transform: "rotate(45deg)",
    textTransform: "uppercase",
  },
  planCardHeader: {
    marginBottom: 16,
  },
  planCardName: {
    margin: 0,
    fontSize: 22,
    fontWeight: 700,
  },
  planCardPrice: {
    marginTop: 4,
  },
  planCardAmount: {
    fontSize: 28,
    fontWeight: 700,
  },
  planCardPeriod: {
    fontSize: 14,
    color: "#9ca3af",
  },
  featureList: {
    margin: "0 0 16px",
    padding: 0,
    listStyle: "none",
  },
  featureItem: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 0",
    borderBottom: "1px solid rgba(63,63,70,0.3)",
    fontSize: 13,
  },
  featureLabel: {
    color: "#d1d5db",
  },
  featureValue: {
    fontWeight: 600,
  },
  planCardAction: {
    marginTop: 16,
    textAlign: "center",
  },
  currentLabel: {
    color: "#22c55e",
    fontWeight: 600,
  },
  planUpgradeBtn: {
    width: "100%",
    padding: "12px",
    border: "none",
    borderRadius: 10,
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  downgradeLabel: {
    fontSize: 13,
    color: "#6b7280",
  },
  lockedSubtitle: {
    margin: "0 0 20px",
    color: "#9ca3af",
  },
  lockedGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))",
    gap: 16,
  },
  lockedItem: {
    display: "flex",
    gap: 16,
    padding: 16,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(63,63,70,0.3)",
    borderRadius: 12,
  },
  lockedIcon: {
    fontSize: 28,
    flexShrink: 0,
  },
  lockedTitle: {
    fontWeight: 600,
    marginBottom: 4,
  },
  lockedDesc: {
    fontSize: 13,
    color: "#9ca3af",
    marginBottom: 4,
  },
  lockedRequired: {
    fontSize: 12,
    color: "#ef4444",
    fontWeight: 500,
  },
  lockedCta: {
    marginTop: 24,
    textAlign: "center",
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    background: "rgba(15,23,42,0.8)",
    border: "1px solid rgba(148,163,184,0.6)",
    borderRadius: 999,
    color: "#e5e7eb",
    fontSize: 13,
    outline: "none",
  },
  tabsRow: {
    display: "flex",
    gap: 12,
    borderBottom: "1px solid rgba(63,63,70,0.6)",
    marginBottom: 24,
  },
  tab: {
    padding: "8px 16px",
    background: "transparent",
    border: "none",
    borderBottom: "2px solid transparent",
    color: "#9ca3af",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
  },
  tabActive: {
    color: "#ffffff",
    borderBottomColor: "#ef4444",
    fontWeight: 600,
  },
};
